const RestaurantsActionTypes = {
    FETCH_RESTAURANTS: 'FETCH_RESTAURANTS',
    FETCH_RESTAURANTS_SUCCESS: 'FETCH_RESTAURANTS_SUCCESS',
    FETCH_RESTAURANTS_FAILURE: 'FETCH_RESTAURANTS_FAILURE',

};

export default RestaurantsActionTypes;